### ISSUE TITLE
Kaggle Dataset Usage

### ISSUE THREAD

**Issue by mathyouf** [liaopeiyuan/artbench#1]
Hello!

How can I use the [artbench10 Kaggle Dataset](https://www.kaggle.com/datasets/alexanderliao/artbench10) once it is downloaded?

<img width="653" alt="Screen Shot 2022-06-26 at 9 55 24 PM" src="https://user-images.githubusercontent.com/19615875/175851484-2a559e06-a1cd-4333-86bf-de5b84e63253.png">

I know this is probably more of a question for Kaggle but I couldn't find any relevant information on the topic.

**Comment by liaopeiyuan** [comment]
the 32x32 version available on Kaggle is created in the same format as the CIFAR-10 dataset: https://www.cs.toronto.edu/~kriz/cifar.html. You may wanna check [torchvision](https://pytorch.org/vision/stable/_modules/torchvision/datasets/cifar.html#CIFAR10)'s implementation of CIFAR-10 loader for how to read it.

**Comment by liaopeiyuan** [comment]
Lemme know if this resolves it. Closing for now.
