### ISSUE TITLE
256x256 Train/Test Splits

### ISSUE THREAD

**Issue by GeorgeCazenavette** [liaopeiyuan/artbench#2]
Hi!

Is there a way to access the Train and Test splits for the 256x256 ImageFolder version?

It seems like all 6000 images for each class are in the same directory.

Thanks!

**Comment by liaopeiyuan** [comment]
The train/test split is the same across all resolutions and is described in the [Metadata](https://drive.google.com/file/d/18B35DO8AONK6x-mBbvboOrqPZOzrKwev/view) file with the `split` column. We will soon release an additional version with train/test folder specified.

**Comment by liaopeiyuan** [comment]
Lemme know if this resolves it. Closing for now.
