### ISSUE TITLE
Error while downloading: daily quota exceeded and it can't be dowloaded''

### ISSUE THREAD

**Issue by ablattmann** [liaopeiyuan/artbench#3]
Hi @Xiuyu-Li and @liaopeiyuan  , 
thanks for creating this neat dataset. 
I just tried to downloading, but no matter which of the provided URLs I am using (artbench-10-32x32, artbench-10-256x256 or the originally sized image) , I always end up with the error 'The daily quota of the file artbench-10-python.tar.gz is exceeded and it can't be downloaded. This is a limitation of Google Drive and can only be overcome by trying again later.'.

It would be awesome if this could be fixed. 

Thx in advance!
Cheers
Andreas

**Comment by liaopeiyuan** [comment]
As denoted, this is a problem on the Google Drive side. You may wanna try the Kaggle mirror instead: https://www.kaggle.com/datasets/alexanderliao/artbench10

**Comment by ablattmann** [comment]
Thank you, this works.
However, I'd be particularly interested in the 256x256 dataset, which is not available via the Kaggle mirror, if I don't miss something. Is there currently a way to download this dataset?

**Comment by liaopeiyuan** [comment]
We've temporarily set up a dropbox link here https://www.dropbox.com/s/70h563tlq5iretb/artbench-10-imagefolder-split.tar?dl=0 and are looking for long-term hosting options.

**Comment by Xiuyu-Li** [comment]
We moved all files except for the original size LSUN datasets to our own server, which should solve the download quota issue for 32x32 and 256x256 datasets. The original size LSUN format datasets can still be accessed through the Google Drive link.
